/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package dam.bucles.interfaz;

import dam.bucles.clases.Funciones;
import java.io.File;
import java.util.ArrayList;
import java.util.List;
import javax.swing.JFileChooser;
import javax.swing.JOptionPane;

public class FormularioPrincipal extends javax.swing.JFrame {

    File origenFicheros = null;
    File destinoFicheros = null;

    Funciones funciones;

    List<File> listaFicherosJava;


    public FormularioPrincipal() {
        initComponents();
        funciones = new Funciones();
        listaFicherosJava = new ArrayList<>();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        btnCarpetaOrigen = new javax.swing.JButton();
        btnCarpetaDestino = new javax.swing.JButton();
        btnMostrarResultado = new javax.swing.JButton();
        btnMostrarResultado1 = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setResizable(false);

        jLabel1.setFont(new java.awt.Font("Dialog", 1, 48)); // NOI18N
        jLabel1.setText("  Buscador WHILE-3000");

        btnCarpetaOrigen.setText("Seleccionar Origen");
        btnCarpetaOrigen.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCarpetaOrigenActionPerformed(evt);
            }
        });

        btnCarpetaDestino.setText("Seleccionar Destino");
        btnCarpetaDestino.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCarpetaDestinoActionPerformed(evt);
            }
        });

        btnMostrarResultado.setText("Mostrar Resultado");
        btnMostrarResultado.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnMostrarResultadoActionPerformed(evt);
            }
        });

        btnMostrarResultado1.setText("Copiar");
        btnMostrarResultado1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnMostrarResultado1ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, 551, Short.MAX_VALUE)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(btnCarpetaOrigen)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(btnCarpetaDestino, javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(btnMostrarResultado, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(btnMostrarResultado1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                                .addGap(208, 208, 208)))))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(20, 20, 20)
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 63, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnCarpetaOrigen, javax.swing.GroupLayout.PREFERRED_SIZE, 69, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnCarpetaDestino, javax.swing.GroupLayout.PREFERRED_SIZE, 69, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 55, Short.MAX_VALUE)
                .addComponent(btnMostrarResultado, javax.swing.GroupLayout.PREFERRED_SIZE, 69, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(30, 30, 30)
                .addComponent(btnMostrarResultado1, javax.swing.GroupLayout.PREFERRED_SIZE, 69, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnCarpetaOrigenActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCarpetaOrigenActionPerformed
        try {
            JFileChooser j = new JFileChooser("C:\\");
            j.setFileSelectionMode(JFileChooser.FILES_AND_DIRECTORIES);
            j.showSaveDialog(null);

            origenFicheros = j.getSelectedFile();

            listaFicherosJava = funciones.ObtenerFicheros(origenFicheros);

        } catch (NullPointerException npe) {
        }
    }//GEN-LAST:event_btnCarpetaOrigenActionPerformed

    private void btnCarpetaDestinoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCarpetaDestinoActionPerformed
        try {
            JFileChooser j = new JFileChooser("C:\\");
            j.setFileSelectionMode(JFileChooser.FILES_AND_DIRECTORIES);
            j.showSaveDialog(null);

            destinoFicheros = j.getSelectedFile();

        } catch (NullPointerException npe) {
        }
    }//GEN-LAST:event_btnCarpetaDestinoActionPerformed

    private void btnMostrarResultado1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnMostrarResultado1ActionPerformed

        if (origenFicheros == null || destinoFicheros == null) {
            JOptionPane.showMessageDialog(null, "No has seleccionado los ficheros de origen o destino");
        } else {
            if (funciones.Guardar(listaFicherosJava, destinoFicheros)) {
                JOptionPane.showMessageDialog(null, "Se ha creado el fichero con los resultados obtenidos");
            } else {
                JOptionPane.showMessageDialog(null, "Ha ocurrido un error");
            }
        }

    }//GEN-LAST:event_btnMostrarResultado1ActionPerformed

    private void btnMostrarResultadoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnMostrarResultadoActionPerformed

        JOptionPane.showMessageDialog(null, "Opcion no disponible");


    }//GEN-LAST:event_btnMostrarResultadoActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(FormularioPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(FormularioPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(FormularioPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(FormularioPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new FormularioPrincipal().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnCarpetaDestino;
    private javax.swing.JButton btnCarpetaOrigen;
    private javax.swing.JButton btnMostrarResultado;
    private javax.swing.JButton btnMostrarResultado1;
    private javax.swing.JLabel jLabel1;
    // End of variables declaration//GEN-END:variables
}
